spring:
    jpa:
        hibernate:
                ddl-auto: create-drop
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    datasource:
            url: "jdbc:mysql://eu-cdbr-west-03.cleardb.net:3306/heroku_d971cc75c42dae9"
            username: b5708b27b90ead
            password: 27c00b1a
            hikari:
                maxLifeTime: 20000


#spring.datasource.url=jdbc:mysql://eu-cdbr-west-03.cleardb.net:3306/heroku_d971cc75c42dae9?serverTimezone=UTC
#spring.datasource.username=b5708b27b90ead
#spring.datasource.password=27c00b1a
#spring.datasource.hikari=maxLifetime:20000
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#server.error.include-message=always
#server.error.include-binding-errors=always
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.show-sql=true
#spring.mvc.pathmatch.matching-strategy=ant-path-matcher
#server.port=5005

